---
title: "MediaTenor Data"
output: 
  html_document:
    fig_width: 10
    theme: "lumen"
    highlight: "tango"
    code_folding: show
    self_contained: true
---


```{r message=FALSE, warning=FALSE, include=FALSE}
library(foreign)
library(tidyr)
library(ggplot2)
library(dplyr)
library(lubridate)
library(readr)
library(plotly)
library(scales)

# Theming
quartzFonts(
  Roboto =
    c("Roboto-Light",
      "Roboto-Bold",
      "Roboto-Regular",
      "Roboto-Thin")
)

theme_set(
  theme_bw(base_family = "Roboto", base_size = 10) +
    theme(
      plot.title = element_text(size = 14,
                                margin = margin(0, 0, 4, 0, "pt")),
      plot.subtitle = element_text(size = 8),
      plot.caption = element_text(size = 6),
      plot.background   = element_rect("#fafafa", "#fafafa"),
      panel.background  = element_rect("#fafafa"),
      panel.border = element_blank()
    )
)

rm(list=ls())
```

```{r eval=FALSE, include=FALSE}
# Import & Manipulate Data

pp_1998_2012 <- read_csv("../data/pp_1998-2012.csv")
```

```{r eval=FALSE, include=FALSE}
### Calculate score
df <- as.tbl(pp_1998_2012) %>%
  mutate(value = ifelse(wertung2=="Ablehn.", -1,0),
         value = ifelse(wertung2== "o. eind.",0, value),
         value = ifelse(wertung2== "Zustimm.",1,value))
```

```{r eval=FALSE, include=FALSE}
df <- df %>%
  # calculate number of obs by medium, p_group, year
  group_by(medium2, p_group2, year) %>%
  add_tally() %>%
  ungroup() %>%
  mutate(count = n) %>%
  select(-n) %>%
  
  # calculate number of obs by medium, year
  group_by(medium2, year) %>%
  add_tally() %>%
  ungroup() %>%
  mutate(sumcount = n) %>%
  select(-n) %>%
  
  # calculate weight
  mutate(weight = count/sumcount) %>%
  
  # calculate weighted values
  mutate(weighted = value * weight)
```

```{r eval=FALSE, include=FALSE}
df.reduced <- df %>% 
  group_by(medium2, p_group2, year) %>%
  summarise(count = n(),
            weighted = mean(weighted),
            wertung = mean(value),
            weight = mean(weight)) %>%
  ungroup() %>%
  mutate(medium = factor(ifelse(grepl("ddeutsche", medium2), "SZ", medium2)),
         p_group = factor(ifelse(grepl("90", p_group2), "Bündnis 90/ Die Grüne", p_group2))) %>%
  select(- c(medium2, p_group2))
```

```{r eval=FALSE, include=FALSE}
### Assign category to medium
daily_print <- c("Die Welt", "F.A.Z.", "SZ", "Fr. Rundschau", "tageszeitung", "Bild", "Berliner")
magazine_print <- c("Focus", "Spiegel", "Die Zeit", "Die Woche", "Rh. Merkur", "Stern", "F.A.S.", "WamS", "BamS", "Super Illu")
news_tv <- c("Tagesthemen", "heute journal", "RTL Aktuell", "Tagesschau", "heute", "ProSieben")
polit_tv <- c("Fakt", "Frontal 21", "Kontraste", "Monitor", "Panorama", "Plusminus", "Report (BR)", "Report (SWR)", "WISO", "Bericht aus Berlin", "Berlin direkt")

df.reduced <- df.reduced %>%
  mutate(category = ifelse(medium %in% daily_print, "daily_print", " "),
         category = ifelse(medium %in% magazine_print, "magazine_print", category),
         category = ifelse(medium %in% news_tv, "news_tv", category),
         category = ifelse(medium %in% polit_tv, "polit_tv", category))

save(df.reduced, file = "../output/mediatenor.Rda")
```

```{r eval=FALSE, include=FALSE}
###### THEMA #########

# select theme (top 20)
df %>% group_by(p_them2) %>%
  tally(sort = T) %>%
  top_n(20) %>%
  select(p_them2) %>%
  mutate(p_thema = ifelse(grepl("anderer Aspekt", p_them2), 
                          "anderer Aspekt des öffentlichen Auftretens", p_them2),
         
         p_thema = ifelse(grepl("enpolitik insgesamt", p_them2), 
                          "Außenpolitik insgesamt", p_thema),
         
         p_thema = ifelse(grepl("Programmatik, Konzepte", p_them2), 
                          "Programmatik, Konzepte, Pläne allgemein", p_thema),
         
          p_thema = ifelse(grepl("Steuerpolitik allgemein/anderes", p_them2), 
                          "Steuerpolitik allgemein/anderes (nicht Ökosteuer, nicht Soli", p_thema),
         
         p_thema = ifelse(grepl("Regierungsf", p_them2), 
                          "Regierungsfähigkeit, Regierungstätigkeit", p_thema),
         
         p_thema = ifelse(grepl("Koalition, Zusammenarbeit von CDU/CSU und SPD", p_them2), 
                          "große Koalition, Zusammenarbeit von CDU/CSU und SPD", p_thema),
         
         p_thema = ifelse(grepl("nderpolitik", p_them2), 
                          "Ausländerpolitik", p_thema)) -> thema

htmlTable::htmlTable(thema, align="l")
```

```{r eval=FALSE, include=FALSE}
df.thema <- df %>% 
  
  mutate(p_thema = ifelse(grepl("anderer Aspekt", p_them2), 
                          "anderer Aspekt des öffentlichen Auftretens", p_them2),
         
         p_thema = ifelse(grepl("enpolitik insgesamt", p_them2), 
                          "Außenpolitik insgesamt", p_thema),
         
         p_thema = ifelse(grepl("Programmatik, Konzepte", p_them2), 
                          "Programmatik, Konzepte, Pläne allgemein", p_thema),
         
          p_thema = ifelse(grepl("Steuerpolitik allgemein/anderes", p_them2), 
                          "Steuerpolitik allgemein/anderes (nicht Ökosteuer, nicht Soli", p_thema),
         
         p_thema = ifelse(grepl("Regierungsf", p_them2), 
                          "Regierungsfähigkeit, Regierungstätigkeit", p_thema),
         
         p_thema = ifelse(grepl("Koalition, Zusammenarbeit von CDU/CSU und SPD", p_them2), 
                          "große Koalition, Zusammenarbeit von CDU/CSU und SPD", p_thema),
         
         p_thema = ifelse(grepl("nderpolitik", p_them2), 
                          "Ausländerpolitik", p_thema)) %>%
  
  group_by(medium2, p_group2, p_thema) %>%
  filter(p_thema %in% thema$p_thema) %>%
  summarise(weighted = mean(weighted),
            wertung = mean(value),
            weight = mean(weight)) %>%
  ungroup() %>%
  mutate(medium = factor(ifelse(grepl("ddeutsche", medium2), "SZ", medium2)),
         p_group = factor(ifelse(grepl("90", p_group2), "Bündnis 90/ Die Grüne", p_group2))) %>%
  select(- c(medium2, p_group2))
```

# Load Data

For details about data description see [here](https://github.com/franziloew/mediabias/blob/master/docs/mediatenor.Rmd)

```{r message=FALSE, warning=FALSE}
load(file = "../output/mediatenor.Rda")
```
