---
title: "MediaTenor Data"
output: 
  html_document:
    fig_width: 10
    theme: "lumen"
    highlight: "tango"
    code_folding: show
    self_contained: true
---


```{r message=FALSE, warning=FALSE, include=FALSE}
library(foreign)
library(tidyr)
library(ggplot2)
library(dplyr)
library(lubridate)
library(readr)
library(scales)
library(htmlTable)
library(Hmisc)
library(labelled)
library(lubridate)
library(gridExtra)

# Theming
quartzFonts(
  Roboto =
    c("Roboto-Light",
      "Roboto-Bold",
      "Roboto-Regular",
      "Roboto-Thin")
)

theme_set(
  theme_bw(base_family = "Roboto", base_size = 10) +
    theme(
      plot.title = element_text(size = 14,
                                margin = margin(0, 0, 4, 0, "pt")),
      plot.subtitle = element_text(size = 8),
      plot.caption = element_text(size = 6),
      plot.background   = element_rect("#fafafa", "#fafafa"),
      panel.background  = element_rect("#fafafa"),
      panel.border = element_blank()
    )
)

rm(list=ls())
col <- RColorBrewer::brewer.pal(6,"Dark2")
```

```{r eval=FALSE, include=FALSE}
library(haven)
pp_1998_2012 <- read_dta("../data/pp_1998-2012.dta")
```

## Prepare Dataframe 
```{r eval=FALSE, include=FALSE}
df <- pp_1998_2012 %>%
  # decode variables
  mutate(p_group = to_character(p_group),
         medium = to_character(medium),
         wertung = as.numeric(remove_labels(wertung)),
         
         #Generate Date-Variable (as.Date function gives NAs)
         date = as.Date(datum, "%Y-%b-%d"),
         month = as.numeric(monat),
         
         # Correct UTF Problems
         medium = factor(ifelse(grepl("ddeutsche", medium), "SZ", medium)),
         p_group = factor(ifelse(grepl("90", p_group), "Bündnis 90/ Die Grüne", p_group))
         )

### Assign category to medium
daily_print <- c("Die Welt", "F.A.Z.", "SZ", "Fr. Rundschau", "tageszeitung", "Bild", "Berliner")
magazine_print <- c("Focus", "Spiegel", "Die Zeit", "Die Woche", "Rh. Merkur", "Stern", "F.A.S.", "WamS", "BamS", "Super Illu")
news_tv <- c("Tagesthemen", "heute journal", "RTL Aktuell", "Tagesschau", "heute", "ProSieben", "Sat.1 News")
polit_tv <- c("Fakt", "Frontal 21", "Kontraste", "Monitor", "Panorama", "Plusminus", "Report (BR)", "Report (SWR)", "WISO", "Bericht aus Berlin", "Berlin direkt")

df <- df %>%
  mutate(category = ifelse(medium %in% daily_print, "daily_print", " "),
         category = ifelse(medium %in% magazine_print, "magazine_print", category),
         category = ifelse(medium %in% news_tv, "news_tv", category),
         category = ifelse(medium %in% polit_tv, "polit_tv", category))

save(df, file = "../output/mediatenorFULLDF.Rda")
```

```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
df.collapsed <- df %>%
  group_by(date, month, medium, p_group, category) %>%
  summarise(obs = n(),
            wertung = mean(wertung, na.rm = T),
            tendenz = mean(tendenz, ra.rm = T),
            kontext = mean(kontext, ra.rm = T)) %>%
  ungroup()

save(df.collapsed, file = "../output/mediatenorCOLLAPSEDDF.Rda")
```

# Load Data

For details about data prepataion see [here](https://github.com/franziloew/mediabias/blob/master/docs/data_prep.Rmd)

```{r message=FALSE, warning=FALSE}
load(file = "../output/mediatenorCOLLAPSEDDF.Rda")
```

# Number of Observations
```{r Number of Observations, echo=FALSE, fig.height=10, fig.width=8, message=FALSE, warning=FALSE}
plot <- df.collapsed %>%
  mutate(year = year(date)) %>%
  group_by(year, medium, category) %>%
  summarise(n=n(),
            obs = sum(obs)) %>%
  ungroup()

p <- plot %>%
  filter(category == "daily_print")
  
p1 <- ggplot(p, aes(year, n, color=medium,
             group = medium)) +
  geom_point() + geom_line() +
  scale_x_continuous(limits = c(1998,2012), breaks = 1998:2012) +
  labs(x="", y="", color="", title = "Tageszeitungen") +
  guides(col = guide_legend(ncol = 1)) +
  theme(legend.position = "right") 

p <- plot %>%
  filter(category == "magazine_print")
  
p2 <- ggplot(p, aes(year, n, color=medium,
                    group = medium)) +
  geom_point() + geom_line() +
  scale_x_continuous(limits = c(1998,2012), breaks = 1998:2012) +
  labs(x="", y="", color="", title = "Magazine und Wochenzeitungen") +
  guides(col = guide_legend(ncol = 1)) +
  theme(legend.position = "right") 


p <- plot %>%
  filter(category == "news_tv")

p3 <- ggplot(p, aes(year, n, color=medium,
                      group = medium)) +
  geom_point() + geom_line() +
  scale_x_continuous(limits = c(1998,2012), breaks = 1998:2012) +
  labs(x="", y="", color="", title = "Nachrichtensendungen") +
  guides(col = guide_legend(ncol = 1)) +
  theme(legend.position = "right") 

p <- plot %>%
  filter(category == "polit_tv")

p4 <- ggplot(p, aes(year, n, color=medium,
                    group = medium)) +
  geom_point() + geom_line() +
  scale_x_continuous(limits = c(1998,2012), breaks = 1998:2012) +
  labs(x="", y="", color="", title = "Politiksendungen") +
  guides(col = guide_legend(ncol = 1)) +
  theme(legend.position = "right") 

grid.arrange(p1, p2, p3, p4, ncol = 1)
```

# Cluster
```{r}
library(cluster)    # clustering algorithms
library(factoextra) # clustering algorithms & visualization
```

## Tageszeitungen
```{r}
df.cluster <- 
  df.collapsed %>%
  filter(!p_group %in% c("Andere Parteien",
                         "Rechtsextreme Parteien")) %>%
  mutate(year = year(date)) %>%
  filter(year < 2006) %>%
  filter(category == "daily_print") %>%
  group_by(medium, p_group, month) %>%
  summarise(wertung = mean(wertung, na.rm=T),
            tendenz = mean(tendenz, ra.rm = T),
            kontext = mean(kontext, ra.rm = T),
            obs = sum(obs)) %>%
  ungroup() %>%
  group_by(medium, month) %>%
  mutate(totalobs = sum(obs)) %>%
  ungroup() %>%
  mutate(weight = obs/totalobs,
         weighted = wertung*weight)
```


### Weighted DF
```{r echo=FALSE}
sequence <- unique(df.cluster$month)
party <- c("CDU/CSU", "SPD")
k_list <- list()
x = 1

for (i in sequence) {
  
  # Long to wide format DF
  df.weighted <- df.cluster %>%
    filter(month == i) %>%
    filter(p_group %in% party) %>%
    select(medium, p_group, weighted) %>%
    spread(p_group, weighted)
  
  # Convert to Matrix & assign rownames
  m.weighted <- as.matrix(df.weighted %>%
                            select(- medium))
  row.names(m.weighted) <- df.weighted$medium
  m.weighted <- na.omit(m.weighted)
  
  # Scale Data
  m.weighted <- scale(m.weighted)
  
  # K-means clustering
  k<- kmeans(m.weighted, centers = 2, nstart = 25)
  
  # Generate DF
  temp <- m.weighted %>% as_tibble() %>%
    mutate(cluster = k$cluster,
           medium = rownames(m.weighted),
           month = i)
  
  # Add to list
  k_list[[x]] <- temp
  x = x+1
  
  p <- ggplot(temp, aes(`CDU/CSU`, SPD, 
                        color=factor(cluster),
             label = medium)) +
  geom_point(show.legend = F) + 
  ggrepel::geom_text_repel(show.legend = F) +
  scale_x_continuous(limits = c(-2,2)) +
  scale_y_continuous(limits = c(-2,2)) +
    labs(title = paste("Year/Month=",i)) +
    geom_polygon(
      alpha = 0.4, 
                 show.legend = F)
  
  # Save
  ggsave(p, file = paste0("figs/cluster_daily_print/cluster",i,".png"))
  
}
```




